---
#- include: srv.yml
- hosts: binarytemple
  user: root
  tasks:
  - name: Install the binarytemple user
    action: user name=binarytemple home=/srv/binarytemple state=present system=yes
  - name: copy binarytemple.co.uk project to filesystem location
    action: git repo="git@bitbucket.org:sentimental/binarytemple.co.uk.git" dest=/srv/binarytemple/repo version=master
  - name: symbolically link /srv/binarytemple.co.uk to /srv/binarytemple/repo/srv 
    action: file src=/srv/binarytemple/repo/srv dest=/srv/binarytemple.co.uk owner=root group=root state=link
  - name: create etc lightttpd directories 
    action: file path=$item mode=0755 state=directory
    with_items: 
    - /etc/lighttpd
    - /etc/lighttpd/conf-available
    - /etc/lighttpd/conf-enabled
  - name: create /etc/lightppd.conf 
    action: template src="../remote/etc/lighttpd/lighttpd.conf" dest="/etc/lighttpd/lighttpd.conf" owner=root group=root mode=644
    notify:
    - restart lighttpd
  - name: install multiple templates
    action: template src="../remote/etc/lighttpd/conf-available/{{item.skey}}" dest="/etc/lighttpd/conf-available/{{item.value}}" owner=root group=root mode=644 backup=no
    with_items: 
     - { skey : '05-auth.conf.j2'              ,value : '05-auth.conf'            }
     - { skey : '10-accesslog.conf.j2'         ,value : '10-accesslog.conf'       } 
     - { skey : '10-cgi.conf.j2'               ,value : '10-cgi.conf'             }
     - { skey : '10-evasive.conf.j2'           ,value : '10-evasive.conf'         }
     - { skey : '10-evhost.conf.j2'            ,value : '10-evhost.conf'          }
     - { skey : '10-expire.conf.j2'            ,value : '10-expire.conf'          }
     - { skey : '10-fastcgi.conf.j2'           ,value : '10-fastcgi.conf'         }
     - { skey : '10-flv-streaming.conf.j2'     ,value : '10-flv-streaming.conf'   }
     - { skey : '10-no-www.conf.j2'            ,value : '10-no-www.conf'          }
     - { skey : '10-proxy.conf.j2'             ,value : '10-proxy.conf'           }
     - { skey : '10-rrdtool.conf.j2'           ,value : '10-rrdtool.conf'         }
     - { skey : '10-simple-vhost.conf.j2'      ,value : '10-simple-vhost.conf'    }
     - { skey : '10-ssi.conf.j2'               ,value : '10-ssi.conf'             }
     - { skey : '10-ssl.conf.j2'               ,value : '10-ssl.conf'             }
     - { skey : '10-status.conf.j2'            ,value : '10-status.conf'          }
     - { skey : '10-userdir.conf.j2'           ,value : '10-userdir.conf'         }
     - { skey : '10-usertrack.conf.j2'         ,value : '10-usertrack.conf'       }
     - { skey : '15-fastcgi-php.conf.j2'       ,value : '15-fastcgi-php.conf'     }
     - { skey : '90-debian-doc.conf.j2'        ,value : '90-debian-doc.conf'      }
    notify:
    - restart lighttpd
  - name: link necessary templates
    action: file src="/etc/lighttpd/conf-available/${item}" dest="/etc/lighttpd/conf-enabled/${item}" owner=root group=root state=link 
    with_items:
    - '10-accesslog.conf'
    - '10-fastcgi.conf'
    - '10-simple-vhost.conf'
    - '10-usertrack.conf'
    notify:
    - restart lighttpd
  - name: make postfix dir 
    action: file path=/etc/postfix mode=0755 state=directory
  - name: copy postfix templates
    action: template src="../remote/etc/postfix/{{item.key}}" dest="/etc/postfix/{{item.value}}" owner=root group=root mode=644 backup=no
    with_items:
     - { key : 'dynamicmaps.cf.j2'         , value : 'dynamicmaps.cf'     }
     - { key : 'main.cf.j2'                , value : 'main.cf'            }  
     - { key : 'master.cf.j2'              , value : 'master.cf'          }
     - { key : 'postfix-files.j2'          , value : 'postfix-files'      }
     - { key : 'postfix-script.j2'         , value : 'postfix-script'     }
     - { key : 'post-install.j2'           , value : 'post-install'       }
     - { key : 'virtual.j2'                , value : 'virtual'            }
    notify:
    - postfix regenerate
  handlers:
    - name: restart lighttpd
      action: service name=lighttpd state=restarted
    - name: postfix regenerate
      action: command "/usr/sbin/postmap /etc/postfix/virtual"
      action: service name=postfix state=restarted
