---
#- include: srv.yml
- hosts: binarytemple
  user: root
  tasks:

  - name: create website directories 
    action: file path=$item mode=0755 state=directory
    with_items: 
    - /srv/binarytemple
    - /srv/lolbags

  - name: Install the binarytemple user
    action: user name=binarytemple home=/srv/binarytemple state=present system=yes
  - name: copy binarytemple.co.uk project to filesystem location
    action: git repo="git@bitbucket.org:binarytemple/binarytemple.co.uk.git" dest=/srv/binarytemple/repo version=master
  - name: symbolically link /srv/binarytemple.co.uk to /srv/binarytemple/repo/srv 
    action: file src=/srv/binarytemple/repo/srv dest=/srv/binarytemple.co.uk owner=root group=root state=link

  - name: Install the lolbags user
    action: user name=lolbags home=/srv/lolbags state=present system=yes
  - name: copy lolbags.com project to filesystem location
    action: git repo="git@github.com:binarytemple/lolbags.github.io.git" dest=/srv/lolbags/repo version=gh-pages
  - name: symbolically link /srv/lolbags.com to /srv/lolbags/repo
    action: file src=/srv/lolbags/repo dest=/srv/lolbags.com owner=root group=root state=link

  - name: create etc lightttpd directories 
    action: file path=$item mode=0755 state=directory
    with_items: 
    - /etc/lighttpd
    - /etc/lighttpd/conf-available
    - /etc/lighttpd/conf-enabled
  - name: create /etc/lightppd.conf 
    action: template src="../remote/etc/lighttpd/lighttpd.conf" dest="/etc/lighttpd/lighttpd.conf" owner=root group=root mode=644
    notify:
    - restart lighttpd
  - name: install multiple templates
    action: template src="../remote/etc/lighttpd/conf-available/{{item}}.j2" dest="/etc/lighttpd/conf-available/{{item}}" owner=root group=root mode=644 backup=no
    with_items: 
     - '05-auth.conf'
     - '10-accesslog.conf'
     - '10-cgi.conf'
     - '10-evasive.conf'
     - '10-evhost.conf'
     - '10-expire.conf'
     - '10-fastcgi.conf'
     - '10-flv-streaming.conf'
     - '10-no-www.conf'
     - '10-proxy.conf'
     - '10-rrdtool.conf'
     - '10-simple-vhost.conf'
     - '10-ssi.conf'
     - '10-ssl.conf'
     - '10-status.conf'
     - '10-userdir.conf'
     - '10-usertrack.conf'
     - '15-fastcgi-php.conf'
     - '90-debian-doc.conf'
    notify:
    - restart lighttpd
  - name: link necessary templates
    action: file src="/etc/lighttpd/conf-available/{{item}}" dest="/etc/lighttpd/conf-enabled/{{item}}" owner=root group=root state=link 
    with_items:
    - '10-accesslog.conf'
    - '10-fastcgi.conf'
    - '10-simple-vhost.conf'
    - '10-usertrack.conf'
    notify:
    - restart lighttpd
  - name: make postfix dir 
    action: file path=/etc/postfix mode=0755 state=directory
  - name: copy postfix templates
    action: template src="../remote/etc/postfix/{{item}}.j2" dest="/etc/postfix/{{item}}" owner=root group=root mode=644 backup=no
    with_items:
     - 'dynamicmaps.cf'
     - 'main.cf'
     - 'master.cf'
     - 'postfix-files'
     - 'postfix-script'
     - 'post-install'
     - 'virtual'
    notify:
    - postfix regenerate
    - postfix restart
  handlers:
    - name: restart lighttpd
      action: service name=lighttpd state=restarted
    - name: postfix regenerate
      action: command /usr/sbin/postmap /etc/postfix/virtual
    - name: postfix restart
      action: service name=postfix state=restarted
