---
- include: srv.yml
- hosts: binarytemple
  gather_facts: False 
  tasks:
  - name: copy poc_stm project to filesystem location
    action: git repo="git@bitbucket.org:binarytemple/poc_stm.git" dest=/srv/poc_stm_repo version=b23f769781436b6487f4e047a6be00aa11d1dc56

#  - name: symbolically link /srv/binarytemple.co.uk to /srv/binarytemple/repo/srv 
#  handlers:
#    - name: restart lighttpd
#      action: service name=lighttpd state=restarted
