---
- include: debian-experimental.yml
- hosts: hastebin
  vars_files:
   - ../vars/hastebin.yml
  user: root
  vars:
  - is_debian: ${ansible_distribution} == 'Debian'
  tasks:
  - name: install redis-server
    action: apt name=redis-server state=installed

  - lineinfile: dest=/etc/ssh/ssh_known_hosts line='|1|KWI6LgcTkLS4a3J/jfyOaS6CIKE=|VIpECtP9TDwqZvzNIUSd01ZyKTI= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' owner=root state=present create=True

  - name: download haste-server
    action: git repo="git@github.com:binarytemple/haste-server.git" dest=/srv/haste-server version=abb49f2cf33560cd9cb0b549c9c8a570dfdad81f 

  - name: install nodejs 
    action: apt name=$item state=latest update_cache=yes cache_valid_time=3600 
    with_items:
    - nodejs
    - npm
    when: is_debian == True

  - name: install sysv init script
    action: template src=../templates/debian-init-template.j2 dest=/etc/init.d/hastebin owner=root group=root mode=0755  
 
  - name: ensure hastebin running
    action: service name=hastebin enabled=true state=running

  - name: install iptables rules 
    action: template src=../templates/iptables-hastebin.j2 dest=/etc/iptables/rules owner=root group=root mode=0600
    notify: reload iptables    

  - name: install node requirements
    action: npm path=/srv/haste-server state=latest

  handlers:
    - name: reload iptables
      action: service name=iptables-persistent state=restarted enabled=true
