---
- hosts: all
  user: root
  vars:
  - is_ubuntu: "{{ansible_distribution}} == 'Ubuntu'"
  tasks:
  - name: install multiple packages
    action: apt name={{item}} state=latest update_cache=yes cache_valid_time=3600 
    with_items:
    - vim 
    - netcat 
    - ngrep
    - tcpdump 
    - emacs 
    - zsh 
    - tmux
    - mailutils
    - git 
    when: is_ubuntu == True
